### ISSUE TITLE
Can't compile *.c and *.s files together in Eclipse C/C++

### ISSUE THREAD

**Issue by sedevdkw** [eclipse-cdt/cdt#796] opened 2024-05-20 07:41 UTC
My project contains a collection of .h, .c, and .s files. When I attempt to compile using _arm-none-eabi-gcc_, only the .c files are compiled into object files, while the compiler doesn't process the .s files. This results in errors during the linking stage, as all the .c and .s files need to be compiled before being linked.

I have successfully compiled in the command line using _arm-none-eabi-gcc_ with the following command:

`arm-none-eabi-gcc -march=armv7-r+fp -mtune=cortex-r5 -mfpu=fpv4-sp-d16 --specs=nosys.specs -T HL_sys_link.ld -Iinclude/ source/*.c source/*.s -o output.o`

However, I am unsure how to instruct the toolchain in Eclipse C/C++ to ensure that .s files are compiled as well. Please assist me with this.

Thank you in advance.

**Comment by jld01** [comment] 2024-05-20 07:51
Duplicate of #795.

**Closed by jld01** 2024-05-20 07:51 UTC
