### ISSUE TITLE
TM Terminal: no  shell prompt with bash or zsh

### ISSUE THREAD

**Issue by space88man** [eclipse-cdt/cdt#831] opened 2024-06-18 23:02 UTC
**Describe the bug**
When I run a local terminal with bash / zsh in TM Terminal, no shell prompt appears.

**To Reproduce**

1. Window -> Preferences  -> TM Terminal -> Local Terminal
2. Shell Command: use /bin/bash or /bin/zsh
3. Open a new Local Terminal
4. No shell prompt appears; no messages in Error log

**Expected behavior**
Shell prompt

**Screenshots**
/bin/bash or /bin/zsh:

![Screenshot from 2024-06-19 06-55-02](https://github.com/eclipse-cdt/cdt/assets/29966967/6e81edd7-447c-4e9d-9cd0-d0859a6c6943)

/bin/fish:

![Screenshot from 2024-06-19 07-01-25](https://github.com/eclipse-cdt/cdt/assets/29966967/0be3decb-394f-4936-a19c-e57fd2df215d)

**Version Information (please complete the following information):**
 - Linux (x86_64, Fedora 40)
 - Eclipse Version from Help -> 2024-06
 - CDT Version from Help -> About -> Installation Details -> 11.6.0

**Additional context**
* both `/bin/bash` `/bin/zsh` show this no-output issue
* shell can be closed with Ctrl+D; shell is shown running using `ps`
* the shell is semi-functional: if I type `emacs` blindly the child program is really run
* programs with text output (e.g. `ls`) don't show output
* `vim`: surprisingly appears on screen; running a program under vim `:! ls` works
* if the shell is `/bin/fish` - it shows prompt: running `/bin/bash` under `/bin/fish` shows the same issue; there is no bash prompt
* with blind bash/zsh: non-working curses programs - top, nano, htop
* with blind bash/zsh: working curses programs - ipython, vim , neovim
* with blind bash/zsh: it is possible to run fish and the prompt appears
* if bash is the shell at the other end of a SSH Terminal it works

## Other OSes
* works on Pop!_OS 22.04, i.e. does not reproduce
* works on Ubuntu 24.04., i.e. does not reproduce

## zsh 
If I remove `~/.zshrc` I will get the zsh customisation process; after `~/.zshrc` is written it then goes into the no-output state

**Comment by space88man** [comment] 2024-06-18 23:15
This looks the same as #776 - so may not be macos specific

**Comment by space88man** [comment] 2024-06-19 13:45
Update: it seems to be related to xterm emulation

What works under Fedora 40:
- start with any working shell 
- `TERM=linux /bin/bash` - works as expected
- `TERM=screen /bin/zsh` - works as expected

**Comment by jonahgraham** [comment] 2024-06-19 17:58
Thanks @space88man you have provided enough information for me to figure out what is going wrong.

The problem is the string terminator implementation in the terminal. Escape strings (like OSC 133 commands) can end with BEL or ESC \. In the terminal only the BEL terminator was implemented:

https://github.com/eclipse-cdt/cdt/blob/ba16b7008df38c09e9d5dabd408ea85fd2db8fbc/terminal/plugins/org.eclipse.tm.terminal.control/src/org/eclipse/tm/internal/terminal/emulator/VT100Emulator.java#L430-L435

Although ESC \ has been part of the spec for a long time, I guess most places didn't use it until recently. gnome started using it very recently with [this commit](https://gitlab.gnome.org/GNOME/vte/-/commit/4d4e4807e1205ea10bca821af30caa0ec70325db) which basically supports https://iterm2.com/documentation-escape-codes.html for allowing terminals to navigate the terminal output better.

For now I can properly ignore the unsupported sequences and I will provide a PR for that in a moment.

**Comment by jonahgraham** [comment] 2024-06-19 18:02
In addition, the terminal didn't properly handle badly formed clients, quoted from [here](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html):

> 
>     Some controls (such as OSC ) introduce a string mode, which is ended
>     on a ST  (string terminator).
> 
>     ECMA-48 describes only correct behavior, telling what types of
>     characters are expected at each stage of the control sequences.  It
>     says that the action taken in error recovery is implementation-
>     dependent.  XTerm decodes control sequences using a state machine.
>     It handles errors in decoding i.e., unexpected characters, by
>     resetting to the initial (ground) state.  That is different from the
>     treatment of unimplemented (but correctly formatted) features.
> 
>     If an application does not send the string terminator, that is also
>     an error from the standpoint of a user.  To accommodate users of
>     those applications, xterm has resource settings which allow
>     workarounds:
> 
>     o   The Linux console's palette sequences do not use a string
>         terminator.  The [brokenLinuxOSC](https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:brokenLinuxOSC) resource setting tells xterm to
>         ignore those particular sequences.
> 
>     o   The terminal should accept single-byte controls within the
>         string.  But some applications omit a string terminator, like
>         the Linux console.  The [brokenStringTerm](https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:brokenStringTerm) resource setting tells
>         xterm to exit string mode if it decodes a common control
>         character such as carriage return before the string terminator.

had the terminal handled it properly we would have been ok too.

**Comment by space88man** [comment] 2024-06-20 00:01
@jonahgraham - can this go into a p2 update before 2024-09?

**Comment by jonahgraham** [comment] 2024-06-20 01:47
Yes it can and will - I will publish an update soon. It would be helpful if you can test it before it is published. In a couple of hours the main branch should be built here https://ci.eclipse.org/cdt/job/cdt/job/main/415/artifact/releng/org.eclipse.cdt.repo/target/repository/ and then I'll backport the fix to the current release branch.

(reopening until fixed on the release branch)

**Comment by space88man** [comment] 2024-06-20 05:42
> It would be helpful if you can test it before it is published.

Tested on 2024-06 by munging the `VT100*.class` files from [terminal.control_5.5.400 jar](https://ci.eclipse.org/cdt/job/cdt/job/main/415/artifact/releng/org.eclipse.cdt.repo/target/repository/plugins/org.eclipse.tm.terminal.control_5.5.400.202406200145.jar) into the existing 5.5.300 jar.

All work - bash, zsh, tmux, screen  as shell commands.

Thank you!

**Comment by jonahgraham** [comment] 2024-07-02 20:04
Fixed on 11.6 branch which should be released soon as 11.6.1

**Closed by jonahgraham** 2024-07-02 20:04 UTC
