### ISSUE TITLE
CDT failed to parse some preprocessed c code

### ISSUE THREAD

**Issue by Neuromancer42** [eclipse-cdt/cdt#133] opened 2022-11-01 14:38 UTC
I am trying use CDT as a frontend of my project, but it seems that the parser cannot correctly generate AST of some preprocessed c code.

```c
extern __inline unsigned long long
__attribute__((__gnu_inline__, __always_inline__, __artificial__))
_mulx_u64 (unsigned long long __X, unsigned long long __Y,
    unsigned long long *__P)
{
  unsigned __int128 __res = (unsigned __int128) __X * __Y;
  *__P = (unsigned long long) (__res >> 64);
  return (unsigned long long) __res;
}

int main() {
    unsigned long long x = 10;
    unsigned long long y = 10;
    unsigned long long z;
    _mulx_u64(x, y, &z);
    return z;
}
```

This is a piece of the code for demo. The code is genenrated by `gcc -E some-code.c`, and is both compilable by `gcc` and `clang` .

In detail,
1. I invoke the parser by the following code:
```java
        FileContent fileContent = FileContent.createForExternalFileLocation("../../../../test.c");
        IScannerInfo scannerInfo = new ScannerInfo(new HashMap<>(), new String[0]);
        IParserLogService log = new DefaultLogService();
        IncludeFileContentProvider emptyIncludes = IncludeFileContentProvider.getEmptyFilesProvider();
        int opts = 0;
        IASTTranslationUnit tu;
        tu = GCCLanguage.getDefault().getASTTranslationUnit(fileContent, scannerInfo, emptyIncludes, null, opts, log);
// some other traversing
        System.out.println(new ASTWriter().write(tu));
```
2. ASTWriter fails with the following pasing problem:
```
Missing ; in file: /.../test.c:6
```
3. Environment: OS: macOS 12.6; JDK: Oracle JDK 11.0.14; gcc: Homebrew GCC 11.3.0_1; clang: Apple clang 13.1.6
4. I have posted a demo project at https://github.com/Neuromancer42/cdt-parser-demo (This is a bnd-workspace project, not a standard eclipse plugin project). The project can be built and run by executing `./gradlew run.cdtdemo` in the project root.

**Comment by jonahgraham** [comment] 2022-11-01 14:53
Can you add instructions on how to build and run your example, I get:

```
$ java cdtdemo.Main
Error: Unable to initialize main class cdtdemo.Main
Caused by: java.lang.NoClassDefFoundError: org/eclipse/core/runtime/CoreException
```

**Comment by jonahgraham** [comment] 2022-11-01 14:58
FWIW the sample you have works if I open it in a CDT editor, but there is something odd happening around the `* __Y;` as if I remove the `;` I don't get an error:

![image](https://user-images.githubusercontent.com/679236/199264316-619700c6-33f1-4cb4-b2be-681e9ec5fc50.png)

 but I do get an error if I remove the `;` on the next line I do:

![image](https://user-images.githubusercontent.com/679236/199264414-537f6fd8-9725-4a7a-b6a3-7bfba9bcd00b.png)

**Comment by Neuromancer42** [comment] 2022-11-01 15:21
> Can you add instructions on how to build and run your example, I get:
> 
> ```
> $ java cdtdemo.Main
> Error: Unable to initialize main class cdtdemo.Main
> Caused by: java.lang.NoClassDefFoundError: org/eclipse/core/runtime/CoreException
> ```

It can be runned by `./gradlew run.cdtdemo`

**Comment by Neuromancer42** [comment] 2022-11-01 15:28
> FWIW the sample you have works if I open it in a CDT editor, but there is something odd happening around the `* __Y;` as if I remove the `;` I don't get an error:
> 
> ![image](https://user-images.githubusercontent.com/679236/199264316-619700c6-33f1-4cb4-b2be-681e9ec5fc50.png)
> 
> but I do get an error if I remove the `;` on the next line I do:
> 
> ![image](https://user-images.githubusercontent.com/679236/199264414-537f6fd8-9725-4a7a-b6a3-7bfba9bcd00b.png)

The strange thing is that the `IASTProblem` (actually `CASTProblemStatement` I think) locates itself at an `8` in `__int128`

**Comment by jonahgraham** [comment] 2022-11-01 15:31
The issue is the `__int128` correct? I am not sure what the solution is, I recommend having a look at the CDT test suite org.eclipse.cdt.core.parser.tests.ast2.AST2TestBase.parse(String, ParserLanguage, boolean, boolean, int) to see if that guides you.

**Comment by Neuromancer42** [comment] 2022-11-02 18:16
Thank you for the hint for debug. I've found the root cause and the solution.

The keyword `__int128` is added into the keyword list of the scanner `CPreprocessor` only when GCC version >= 4.7. By default, no GCC version is set and thus the keyword is not identified.

So the solution is setting GCC version number by setting the key `__GNUC__` and `__GNUC_MINOR__` in the `Map<String, String> definedSymbols`. Then `__int128` can be parsed.

**Comment by jonahgraham** [comment] 2022-11-02 18:39
That is great to hear. I'll close this issue now.

**Closed by jonahgraham** 2022-11-02 18:39 UTC
