### ISSUE TITLE
100% CPU when opening terminal and takes lot of time

### ISSUE THREAD

**Issue by adangel** [eclipse-cdt/cdt#835] opened 2024-06-21 11:21 UTC
**Describe the bug**
Debian Testing recently fixed [#1029152](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1029152) which has the consequence that the hard limit for NOFILE is now much bigger than before. That means that `_SC_OPEN_MAX` is now as big as `1073741816` instead of only `1048576`.

When closing the file descriptors of the forked child process, the for-loop now takes a lot of time:
https://github.com/eclipse-cdt/cdt/blob/0583a0568dafd3143f68ca5fdf219a4496dd5292/core/org.eclipse.cdt.core.native/native_src/unix/exec_pty.c#L110-L117

Eventually it finished and the terminal is working. But every time a new terminal window is opened, it takes again a lot of time (couple of minutes).

**To Reproduce**
1. Make sure you have a big number in `/proc/sys/fs/nr_open`: `echo 1073741816 > /proc/sys/fs/nr_open`
2. Start eclipse
3. Verify the limits of the eclipse process, e.g. `prlimit --nofile -p <PID OF eclipse>` should output:
   ```
   RESOURCE DESCRIPTION                    SOFT       HARD UNITS
   NOFILE   max number of open files 1073741816 1073741816 files
   ```
   If the soft limit is lower, you can set it with `prlimit --nofile=1073741816:1073741816 -p <PID OF eclipse>`
 
4. Open a new local terminal
5. It takes a long time until the prompt is shown

**Expected behavior**
The prompt is shown instantly and the terminal is directly usable.

**Version Information (please complete the following information):**
 - OS and OS Version/extra details: Linux, Debian Testing
 - Eclipse Version from Help: 2024-06 (4.32.0)
 - CDT Version from Help -> About -> Installation Details -> Features tab: 11.6.0.202403071917

**Additional context**

This is the same problem as described in https://github.com/JetBrains/pty4j/issues/147 .
It seems, that pty4j and the terminal functionality from eclipse-cdt stem from the same origin - [ELT](https://code.google.com/archive/p/elt/). Maybe the same fix (https://github.com/JetBrains/pty4j/commit/04685d870fd09371fe8580f664be5aea41de5b2c) from pty4j can be reused here?

**Comment by jonahgraham** [comment] 2024-06-21 14:08
Thanks @adangel for this detailed report. Since pty4j uses code originally from Eclipse CDT I hope we can bring the fix back to CDT easily enough.

Do you have the knowledge/capacity to apply the fix to CDT? I can help support the development.

> It seems, that pty4j and the terminal functionality from eclipse-cdt stem from the same origin - [ELT](https://code.google.com/archive/p/elt/). Maybe the same fix (https://github.com/JetBrains/pty4j/commit/04685d870fd09371fe8580f664be5aea41de5b2c) from pty4j can be reused here?

FWIW I think all of it was derived from the CDT version. The code's [blame is from 2004](https://github.com/eclipse-cdt/cdt/blame/3cf0297769e5cfb91823e93ce570120a75fe01ce/core/org.eclipse.cdt.core.linux/library/exec_pty.c#L108-L115) and the code was introduced to fix https://bugs.eclipse.org/bugs/show_bug.cgi?id=27663

**Comment by adangel** [comment] 2024-06-22 07:34
@jonahgraham see #840 - hope this is OK copying from EPL 1.0 to EPL 2.0...

**Comment by jonahgraham** [comment] 2024-06-23 16:10
Thank you @adangel for applying the fix to CDT's code base. I have tested #840 on my machine and I can see the before and after behaviour.

_reopening because it auto-closed when applied to main branch, I want to backport this to 11.6 branch, which is the current target milestone of this issue._

**Comment by haukehoffmann** [comment] 2024-06-24 10:45
Hi [adangel](https://github.com/adangel), many thanks for your post. It saved my day. 

My eclipse (CDT) got stuckend with the command:
`CDT Scanner Discovery: Invoking Command: gcc -E -P -v -dD spec.c`
and a `echo 1048576  > /proc/sys/fs/nr_open` fixed it quickly for now.

I'm using the following versions:
Debian Testing Linux
Eclipse Version: 2024-06 (4.32.0), Build id: 20240606-1231

**Comment by markusdrescher** [comment] 2024-06-27 21:46
Hi @jonahgraham @adangel,

thanks for the fix. I also stumbled across this issue on Debian unstable. I've downloaded libspawner.so from the PR into my eclipse installation, i.e. into configuration/org.eclipse.osgi/102/0/.cp/os/linux/x86_64/
to test if the issue is gone with Eclipse 2024-06. That is the case for instance when _running_ a program via CDT. However, trying to _debug_ it via CDT, it times out with a popup message: "Could not determine GDB version using command: gdb --version"

So using the workaround echo 1048576  > /proc/sys/fs/nr_open helps in that case.
Is there something similar in the codebase of CDT for debugging?

**Comment by jonahgraham** [comment] 2024-06-27 22:59
Thanks @markusdrescher for highlighting this. I have reproduced the error launching debug session with the unfixed CDT and with the fix in #840. I see the CPU at 100% for 10 seconds, and then the error. The 10 seconds is because of:

https://github.com/eclipse-cdt/cdt/blob/5654112209d440469e40660c946ffdee3daa938f/dsf-gdb/org.eclipse.cdt.dsf.gdb/src/org/eclipse/cdt/dsf/gdb/launching/LaunchUtils.java#L338

I am now looking to see if we need to apply the same fix from #840 to somewhere else in CDT.

**Comment by jonahgraham** [comment] 2024-06-27 23:09
Indeed - the same fix is needed here: https://github.com/eclipse-cdt/cdt/blob/c598eedffaa71e9beeaecfe052865cf7bc6615f7/core/org.eclipse.cdt.core.native/native_src/unix/exec_unix.c#L85

**Comment by jonahgraham** [comment] 2024-06-27 23:26
@markusdrescher You can pull the updated libspawner out of PR #846 libspawner.so ([x86_64](https://github.com/jonahgraham/cdt/blob/fix-closing-all-fds-part2/core/org.eclipse.cdt.core.linux.x86_64/os/linux/x86_64/libspawner.so)) 

Once I get a clean build I should be able to merge this and then backport all the changes to CDT 11.6 release branch.

**Comment by hansiglaser** [comment] 2024-06-29 12:44
Also STM32CubeIDE suffers from this problem, see https://community.st.com/t5/stm32cubeide-mcus/cubeide-does-not-start-and-spawner-reaper/m-p/690290
Thanks for fixing!

**Comment by rgrr** [comment] 2024-07-01 07:03
I can confirm that this also fixes long delays in "Build Targets".

Thank you for the fix.

**Comment by markusdrescher** [comment] 2024-07-01 19:09
> @markusdrescher You can pull the updated libspawner out of PR #846 libspawner.so ([x86_64](https://github.com/jonahgraham/cdt/blob/fix-closing-all-fds-part2/core/org.eclipse.cdt.core.linux.x86_64/os/linux/x86_64/libspawner.so))
> 
> Once I get a clean build I should be able to merge this and then backport all the changes to CDT 11.6 release branch.
Fix confirmed on my side for the Debug issue.

Thank you for fixing these issues on such a short notice. Remarkable. Keep up the good work!

**Comment by jonahgraham** [comment] 2024-07-03 01:16
Once the mirrors do their thing Check for Updates in Eclipse will pick up this fix (assuming that https://download.eclipse.org/tools/cdt/releases/11.6/ or https://download.eclipse.org/tools/cdt/releases/latest are listed in available software sites)

**Closed by jonahgraham** 2024-07-03 01:16 UTC
