### ISSUE TITLE
Refresh Action is missing from all Views.

### ISSUE THREAD

**Issue by raghucssit** [eclipse-cdt/cdt#922] opened 2024-10-19 15:23 UTC
The below Refresh Action is not shown on latest CDT package 2024-09.
![378094418-00ab5ab8-4b6f-475f-8923-cda5cf288743](https://github.com/user-attachments/assets/dbe06afd-b771-4413-91e8-6b375f5cc7a7)

I don't see any preference to turn it off. But i can see code still there
https://github.com/eclipse-cdt/cdt/blob/27b8da4ecd7f7e69e082bff3fe6062d5e60fa40c/dsf/org.eclipse.cdt.dsf.ui/plugin.xml#L68

But it is not shown on any Views.
I wanted to migrate this Action also to cdt debug context.

**Comment by jonahgraham** [comment] 2024-10-19 15:24
Duplicate of #920 - please see that issue

**Closed by jonahgraham** 2024-10-19 15:24 UTC
