### ISSUE TITLE
Local terminal window doesn't open on MacOS

### ISSUE THREAD

**Issue by odrotbohm** [eclipse-cdt/cdt#429] opened 2023-06-19 12:51 UTC
When I open a local terminal window from with an STS Installation (Eclipse platform 4.28, Terminal 11.2.0.202303131754). I've seen this issue pop up for quite a while (months), so I don't think this is necessarily related to the latest release.

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', /Users/distiller/project/desktop/lib/alacritty_terminal/src/grid/mod.rs:467:14
                                                                note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

There's no user `distiller` on my machine.

**Comment by jonahgraham** [comment] 2023-06-19 14:03
That error message looks to me like the terminal emulator is throwing an error and the message is coming from their debug information. I assume [alacritty terminal](https://github.com/alacritty/alacritty) do builds with a user called distiller.

What I don't know is how alacritty fit in with Eclipse in this context. My understanding is that when we open a local terminal the code simply launches the user specified shell, defaulting to /bin/sh:


I'll see if I can find a mac to try this on with the latest Eclipse IDE, but if you have more info that would be very useful.

**Comment by jonahgraham** [comment] 2023-06-19 14:05
Here is a screenshot showing the dialog I am referring to, are you using the default here, or something else, perhaps related to alacritty terminal?

![image](https://github.com/eclipse-cdt/cdt/assets/679236/85f32067-2598-442f-b732-dcd5e928f903)

**Comment by odrotbohm** [comment] 2023-06-19 16:04
Thanks for looking into this so quickly. In my installation, this field has a value of `/opt/homebrew/bin/bash`. This resolves to a particular installation of `bash`

```
$ ls -la /opt/homebrew/bin/bash
lrwxr-xr-x  1 odrotbohm  admin  30 Dec 15  2022 /opt/homebrew/bin/bash -> ../Cellar/bash/5.2.15/bin/bash
```

It's also the shell running in my local Terminal application and it works fine there:

```
$ echo $0
/opt/homebrew/Cellar/bash/5.2.15/bin/bash
```

I've tried to switch to `/bin/bash` but that leads to the same error as originally reported. Using `/bin/sh`, however, makes the error disappear. I'd understand that you'd want to close this as "downstream user error". Any idea what could cause the shell working in MacOS' Terminal app, but not from within Eclipse? Both VS Code's and IDEA's integration works just fine.

**Comment by jonahgraham** [comment] 2023-06-19 16:50
I don't want to dismiss as downstream user error without understanding *why* Eclipse is triggering it. Best outcome is that we create a bug report to someone that has actionable change to be made.

I don't really know what the difference is between bash and sh on your machine. But the fact that  alacritty is being mentioned in the error makes me wonder if you have a `.bashrc` or similar (e.g. bash profile, /etc/ something, not sure what the full list is) that is invoking some part of alacritty and then alacritty is querying the running terminal emulator (i.e Eclipse TM Terminal) and Eclipse TM Terminal is sending back some unexpected response causing the crash. (Querying, or maybe reading an environment variable like `TERM` that [CDT sets](https://github.com/eclipse-cdt/cdt/blob/7c8bb9f00ef0d5e3ff493bc0c944519a3e476da2/terminal/plugins/org.eclipse.tm.terminal.view.core/src/org/eclipse/tm/terminal/view/core/utils/Env.java#L67))

**Comment by odrotbohm** [comment] 2023-06-19 21:46
That's been a great pointer. Once I removed the integration for [Fig](https://fig.io/) from my `~/.bashrc`, the shell starts fine in Eclipse. The inclusion at the top adds:
```
[ -x ~/.local/bin/fig ] && eval "$(~/.local/bin/fig init bash pre --rcfile bashrc)"
```
the one at the bottom includes
```
[ -x ~/.local/bin/fig ] && eval "$(~/.local/bin/fig init bash post --rcfile bashrc)"
```
Might at least be helpful for others running into that issue. Is there anything further I can do to be helpful in improving the state of affairs?

**Comment by jonahgraham** [comment] 2023-06-20 17:39
I got hold of a mac and was able to reproduce it. Next step is to narrow down why and file a bug report with someone (fig it seems). I'll try for a bit to see what I can narrow down.

**Comment by jonahgraham** [comment] 2023-06-20 18:37
I have filed a bug with fig - https://github.com/withfig/fig/issues/2600 

I think TM Terminal is not responding as expected to fig, hopefully with some feedback from https://github.com/withfig/fig/issues/2600 we can change TM Terminal to respond correctly. Hopefully the fig folk can avoid the crash and simply disable fig if it isn't supported in TM Terminal as I don't know what it would take to support it fully.

**Comment by jonahgraham** [comment] 2023-09-05 18:02
I don't think that fig are likely to fix this issue anytime soon - fig is either going to have a lot of good things happen soon, or it may no longer exist in the near future due to the recent [news](https://fig.io/blog/post/fig-joins-aws) of their acquisition by Amazon AWS. Best bet is to disable/uninstall fig.

As such I am going to close this as nothing more is planned in CDT.

**Closed by jonahgraham** 2023-09-05 18:02 UTC
Labels: terminal, Waiting for feedback

**Comment by odrotbohm** [comment] 2023-09-05 21:20
Thanks for all the time you invested in this, Jonah! 🙇👍
