### ISSUE TITLE
Type of arithmetic conversion is wrong for combinations of signed/unsigned types with different rank but same size

### ISSUE THREAD

**Issue by PhilippWendler** [eclipse-cdt/cdt#265] opened 2023-01-30 13:14 UTC
There is a bug in the logic that CDT uses for computing the result type of a "usual arithmetic conversion" according to § 6.3.1.8 of the C standard, which is used for many operators.

The code for this is here (introduced by 16944a0de71433953e8078b854426ae327560f7d): https://github.com/eclipse-cdt/cdt/blob/b7fac2cfafa56a79ee1cea6ca8e6deb5416efbd6/core/org.eclipse.cdt.core/parser/org/eclipse/cdt/internal/core/dom/parser/ArithmeticConversion.java#L199-L210

The respective snippet of the C standard says (taken from C11 § 6.3.1.8 (1)):
> Otherwise, if the operand that has unsigned integer type has rank greater or equal to the rank of the type of the other operand, then the operand with signed integer type is converted to the type of the operand with unsigned integer type.
>
> Otherwise, if the type of the operand with signed integer type can represent all of the values of the type of the operand with unsigned integer type, then the operand with unsigned integer type is converted to the type of the operand with signed integer type.
>
> Otherwise, both operands are converted to the unsigned integer type corresponding to the type of the operand with signed integer type.

The first case is implemented correctly.
However, the second case uses the logic `signedRank.ordinal() > unsignedRank.ordinal()` to check "if the type of the operand with signed integer type can represent all of the values of the type of the operand with unsigned integer type". This is wrong for combinations of types that have different ranks but the same size, because then the signed type can *not* represent all values of the unsigned type.

This leads for example to wrong results from `getExpressionType()` on operators using arithmetic conversion.
Concrete cases where this produces a wrong result are `signed long` and `unsigned int` on 32-bit x86 (returned type is `signed long` but should be `unsigned long`) or `signed long long` and `unsigned long` on 64-bit x86.

As a fix, line 205 should compare the sizes of the two types. I think the assumption that a signed type with larger size than an unsigned type can represent all of the unsigned type's values holds.

Note:
- The last `return` statement in the above code is actually dead code right now (both if branches have exactly opposite conditions), also indicating that there is a bug here.
- The existence of this problem was already [acknowledged by the original submitter of the fix](https://bugs.eclipse.org/bugs/show_bug.cgi?id=231859#c7).

**Comment by jonahgraham** [comment] 2023-01-30 13:55
Thanks @PhilippWendler for the bug report. Are you considering providing a PR to test and fix this?

**Comment by PhilippWendler** [comment] 2023-01-30 14:44
Unfortunately, I have no experience developing inside CDT, and I think it would take me too long to get started. I am glad to be of assistance and I tried to make the issue as detailed as possible, but I would prefer if somebody else could implement the actual fix.

**Comment by jonahgraham** [comment] 2023-01-30 14:54
I think you underestimate your abilities. Your OP shows good understanding of the problem and you have found where in the code it goes wrong. Realistically this issue won't be addressed by anyone else as there is no one available to look into this as it has been like this for ~13 years and the authors who wrote that code are not active in CDT anymore. If you and/or your organization cannot provide a fix, I recommend hiring someone who can tackle the problem on your behalf. Feel free to send an email to [cdt-dev](https://github.com/eclipse-cdt/cdt/blob/main/CONTRIBUTING.md#contact) if you want to try to find someone that way, or send me an email and I can try to connect you with someone.

**Comment by i-garrison** [comment] 2023-01-30 20:36
> I am glad to be of assistance and I tried to make the issue as detailed as possible

Hi @PhilippWendler could you please provide a test where you do see the issue now?

I decided to look into this and can confirm the issue is as described, should be fixed by https://github.com/eclipse-cdt/cdt/pull/269

...but my naive test below stumbles upon yet another issue (probably types are not considered by EvalBinary logic):
```c++
template <typename SignedType, typename UnsignedType>
constexpr bool calculate(SignedType x, UnsignedType y) {
    if (sizeof(x) == sizeof(y)) {
        return x - y >= 0;
    } else {
        return true;
    }
}
constexpr auto test_32 = calculate<signed long, unsigned int>(1, 2);
constexpr auto test_64 = calculate<signed long long, unsigned long>(1, 2);
```
Here both `test_32` and `test_64` evaluate to false on x86-64 for me so there should be different test.

**Comment by PhilippWendler** [comment] 2023-01-31 07:03
Thanks a lot! I know nothing about C++, though.

My original C code was this:
```c
int main(void) {
  signed long int x = 0;

  if ( -(1u > x ? 1u : x) <= 0 ) {
    return 1;
  }
  return 0;
}
```
Compiled with `gcc -m32`, this binary produces exit code 0, and I can confirm with a `_Static_assert` that the type of `(1u > x ? 1u : x)` is `unsigned long int`. But if I parse this with CDT and call `getExpressionType()` on the `IASTConditionalExpression`, I get `long int`. In C, The type of the ternary operators is based on the usual arithmetic conversions of its second and third operand.

**Closed** 2023-02-04 14:55 UTC
Labels: language
