### ISSUE TITLE
Invalid template Arguments for std::map in Eclipse 2023-12 with GCC version 13.2.0

### ISSUE THREAD

**Issue by VietHungPhan** [eclipse-cdt/cdt#677] opened 2024-01-18 14:16 UTC
Hi,
I always get the error "Invalid template Arguments" for std::map in Eclipse 2023-12 with linux GCC version 13.2.0. The __cplusplus is set to 201103. Below is my codes.

![image](https://github.com/eclipse-cdt/cdt/assets/43219867/f11e14f4-84d4-4520-a192-e21fc1f6a476)
****

**Comment by i-garrison** [comment] 2024-01-18 14:38
Likely a duplicate of #438 too.

**Comment by jonahgraham** [comment] 2024-01-18 15:06
Hi @VietHungPhan - the fix to Issue #438 that @i-garrison implemented is available in the latest developer build (2024-03 M1) available [here](https://www.eclipse.org/downloads/packages/release/2024-03/m1). That build contains [numerous fixes](https://github.com/eclipse-cdt/cdt/pulls?q=is%3Apr+is%3Aclosed+label%3Alanguage+milestone%3A11.5.0) to language support so any early testing of that build would be very much appreciated.

**Comment by VietHungPhan** [comment] 2024-01-18 16:28
Thanks. I will check it.
BR,Viet-Hung Phan

    On Thursday, January 18, 2024 at 10:06:27 a.m. EST, Jonah Graham ***@***.***> wrote:  
 
 


Hi @VietHungPhan - the fix to Issue #438 that @i-garrison implemented is available in the latest developer build (2024-03 M1) available here. That build contains numerous fixes to language support so any early testing of that build would be very much appreciated.

**Comment by KarlOfDuty** [comment] 2024-01-31 12:59
I had the same issue and the dev build fixed it for me, thanks!

**Comment by jonahgraham** [comment] 2024-02-02 22:17
> I had the same issue and the dev build fixed it for me, thanks!

Thank you for reporting back. That is really helpful.

I am going to close this with thanks to all involved.

**Closed by jonahgraham** 2024-02-02 22:17 UTC
